SeaLion.create([
{:name => "Max", :gender => "Male"},
{:name => "Kurt", :gender => "Male"},
{:name => "Kevin", :gender => "Male"},
{:name => "Kiran", :gender => "Male"},
{:name => "Angel", :gender => "Female"},
{:name => "Eveanandi", :gender => "Female"},
{:name => "Natalia", :gender => "Female"},
{:name => "Ryan I.", :gender => "Male"},
{:name => "Benjamin", :gender => "Male"},
{:name => "Malcolm", :gender => "Male"},
{:name => "Lauren", :gender => "Female"},
{:name => "Daniel", :gender => "Male"},
{:name => "Sam", :gender => "Female"},
{:name => "Stephanie", :gender => "Female"},
{:name => "Tara", :gender => "Female"},
{:name => "Tracy", :gender => "Female"},
{:name => "Hoa", :gender => "Male"},
{:name => "Ryan B.", :gender => "Male"},
])
